name: how_to_do
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  url_launcher: ^6.3.2
  http: ^1.5.0
  get_storage: ^2.1.1
  logger: ^2.6.1
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_bottom_navigation_bar: ^1.4.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  

flutter:


  uses-material-design: true

  # To add assets to your application
  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - lib/l10n/en.json
    - lib/l10n/ar.json



  # To add custom fonts to your application
  fonts:
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: PoppinsMediumItalic
      fonts:
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

